# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['backend/main.py'],
    pathex=[],
    binaries=[],
    datas=[('.env', '.')],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'backend',
        'backend.config',
        'backend.main',
        'backend.database',
        'backend.database.connection',
        'backend.database.models',
        'backend.database.migrations',
        'backend.routers',
        'backend.routers.campaigns',
        'backend.routers.posts',
        'backend.routers.products',
        'backend.routers.metrics',
        'backend.routers.analytics',
        'backend.routers.ai_analysis',
        'backend.routers.settings',
        'backend.connectors',
        'backend.connectors.base',
        'backend.connectors.reddit',
        'backend.connectors.youtube',
        'backend.connectors.twitter',
        'backend.connectors.discord',
        'backend.connectors.hackernews',
        'backend.connectors.manual',
        'backend.ai',
        'backend.ai.analyzer',
        'backend.ai.embedder',
        'backend.ai.prompts',
        'backend.ai.scheduler',
        'backend.services',
        'backend.services.metric_collector',
        'backend.services.daily_pipeline',
        'aiosqlite',
        'sqlalchemy.dialects.sqlite',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'numpy', 'pandas', 'matplotlib', 'scipy', 'sklearn', 'scikit-learn',
        'PIL', 'Pillow', 'cv2', 'opencv', 'tensorflow', 'torch', 'torchvision',
        'keras', 'jupyter', 'notebook', 'IPython', 'ipykernel', 'ipywidgets',
        'bokeh', 'plotly', 'seaborn', 'sympy', 'astropy', 'numba',
        'dask', 'distributed', 'cupy', 'h5py', 'tables', 'pytables',
        'zmq', 'pyzmq', 'tornado', 'twisted', 'gevent',
        'tkinter', '_tkinter', 'Tkinter', 'wx', 'PyQt5', 'PyQt6',
        'PySide2', 'PySide6', 'gi', 'gtk',
        'conda', 'anaconda', 'spyder', 'pytest',
        'docutils', 'sphinx', 'babel', 'lxml',
        'cryptography', 'paramiko', 'fabric',
        'nltk', 'spacy', 'gensim', 'transformers',
        'beautifulsoup4', 'bs4', 'scrapy',
        'celery', 'kombu', 'redis',
        'psycopg2', 'pymysql', 'pymongo',
        'pyarrow', 'parquet',
        'networkx', 'igraph',
        'statsmodels', 'patsy',
        'cython', 'numexpr',
        'openpyxl', 'xlrd', 'xlwt',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='marketing-engine-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
